#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf constant/polyMesh/blockMeshDict
rm -f 0/cellToRegion*
rm -rf 0/fluid
rm -rf 0/solid
rm -f constant/cellToRegion*
rm -rf constant/polyMesh/boundary
rm -rf constant/fluid/polyMesh
rm -rf constant/solid
rm -rf VTK
rm -rf dynamicCode
rm -f post*


