#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

#------------------------------- solarEnergy4Foam project -------------------------------#
#Author
    #Ehsan Golab, SUT. All rights reserved.
    #Ehsan1996Golab@gmail.com

#--------------------------------------------------------------------------------------#

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# cleancase is function that removes the files and directories.(rm -f : remove the file, rm -r : remove the directory).
cleancase ()
{
    rm -r Gnu*
    rm -r processor*
}


# (getApplication) is an command to find the solver name from the controlDict file. Also, ($) use for the variable.
application=$(getApplication)

#cleancase
#./Allclean


echo run blockMesh ...
m4 -P constant/polyMesh/blockMeshDictTrapezoid.m4 > constant/polyMesh/blockMeshDict
blockMesh
#checkMesh



# it can be used to create multi zones
rm -rf constant/polyMesh/sets
setSet -batch PV.setSet
rm constant/polyMesh/sets/*_old
rm constant/polyMesh/sets/*_old.gz
setsToZones -noFlipMap
splitMeshRegions -cellZones -overwrite

mkdir -p 0.1/channel
mkdir -p 0.1/PV

cp 0/* 0.1/channel/
cp 0/* 0.1/PV/

changeDictionary -region channel
changeDictionary -region PV


echo run solver ...
#$application
chtMultiRegion4SEFoam

# -------------------------------------------------------------------------- end-of-file






