#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf constant/polyMesh/blockMeshDict
rm -f 0/cellToRegion*
rm -rf 0/channel
rm -rf 0/metalSheet
rm -rf 0/fin*
rm -f constant/cellToRegion*
rm -rf constant/polyMesh/boundary
rm -rf constant/channel/polyMesh
rm -rf constant/metalSheet
rm -rf constant/fin*
rm -rf VTK
rm -rf dynamicCode
rm -f post*


