#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

#------------------------------- hemodynamic4Foam project -------------------------------#
#Author
    #Ehsan Golab, SUT. All rights reserved.
    #Ehsan1996Golab@gmail.com

#--------------------------------------------------------------------------------------#

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# cleancase is function that removes the files and directories.(rm -f : remove the file, rm -r : remove the directory).
cleancase ()
{
    rm -r Gnu*
    rm -r processor*
}


# (getApplication) is an command to find the solver name from the controlDict file. Also, ($) use for the variable.
application=$(getApplication)

#cleancase
#./Allclean


echo run blockMesh ..
m4 -P constant/polyMesh/blockMeshDictSquare.m4 > constant/polyMesh/blockMeshDict
blockMesh
#checkMesh


# it can be used to create multi zones
rm -rf constant/polyMesh/sets
setSet -batch makeCellSets.setSet
rm constant/polyMesh/sets/*_old
rm constant/polyMesh/sets/*_old.gz
setsToZones -noFlipMap
splitMeshRegions -cellZones -overwrite

mkdir -p 0.1/channel
mkdir -p 0.1/metalSheet
mkdir -p 0.1/fin1
mkdir -p 0.1/fin2
mkdir -p 0.1/fin3

cp 0/* 0.1/channel/
cp 0/* 0.1/metalSheet/
cp 0/* 0.1/fin1/
cp 0/* 0.1/fin2/
cp 0/* 0.1/fin3/

changeDictionary -region channel
changeDictionary -region metalSheet
changeDictionary -region fin1
changeDictionary -region fin2
changeDictionary -region fin3


echo run solver ...
#$application
chtMultiRegionSimple4SEFoam
#streamFunction

# -------------------------------------------------------------------------- end-of-file






